# Generated by Django 2.1 on 2018-08-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_application_hosttoapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hosttoapp',
            name='aobj',
        ),
        migrations.RemoveField(
            model_name='hosttoapp',
            name='hobj',
        ),
        migrations.AddField(
            model_name='application',
            name='relation',
            field=models.ManyToManyField(to='cmdb.Host'),
        ),
        migrations.DeleteModel(
            name='HostToApp',
        ),
    ]
